### ISSUE TITLE
procgen

### ISSUE THREAD

**Issue by hlsafin** [schmidtdominik/Rainbow#1]
Is it possible to create the testing env for procgen so that you can see the generalization performance? I am having difficult implementing it, since i'm using from 'procgen import ProcgenEnv". 

Thank you

**Comment by schmidtdominik** [comment]
You can modify the `env_wrappers.create_procgen_env` function to create the procgen env with other parameters (such as specific seeds). For example, set it to use a fixed set of seeds during training and then evaluate it on a different set. Does that help?

**Comment by hlsafin** [comment]
Right, but the idea being you need two sets of different environment, correct? one only has access to, lets say 500 seed, and the testing env has access to any random seed. And you want to stop learning when your on the test env. 

I tried doing this approach but its quite difficult with SubprocVec, DummyVec since there seems to be memory leak somewhere.

 Also, there is memory leak issue even with other environments, I'm not sure if your facing the same issues as I am. If possible, maybe you can list all the dependencies your currently running on your environment(or create dockerfile). Sorry if this is too much to ask. I'm very interested your implementation, and your work is awesome! 
Thank you
